pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'EC-GCP-Provision'
  version: '1.0.0'
  description: 'This plugin integrates with Google Cloud Platform to provision new resources from the pre-defined resource templates.'
  author: 'Polina'
  supportUrl: 'pshubina@cloudbees.com'
  category: 'Resource Management'
  shell: 'ec-groovy'

# Plugin configuration description
configuration:
  # This is a shell used for checking connection
  shell: 'ec-groovy'
  # A script for checking connection will be generated
  checkConnection: 'true'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
  -
    name: config
    documentation: The name for the created configuration
    required: true
    type: entry
    label: Configuration Name
  -
    name: desc
    documentation: Description for the configuration
    required: false
    type: entry
    label: Description
  -
    name: projectId
    documentation: Project ID for the main project
    required: true
    type: entry
    label: Project Id
  -
    name: zone
    required: true
    type: entry
  -
    name: credential
    documentation: Service account key in JSON format
    required: true
    type: credential
    credentialType: key
    label: Credential

properties:
  ec_dsl_libraries_path: agent/deps/libs
  ec_configurations: ec_plugin_cfgs
  ec_cloudprovisioning_plugin:
    configurationLocation: ec_plugin_cfgs
    displayName: GCP
    hasConfiguration: 1
    operations:
      createConfiguration:
        procedureName: CreateConfiguration
        ui_formRefs:
          parameterForm: 'procedures/CreateConfiguration/ec_parameterForm'
        parameterRefs:
          configuration: config
      deleteConfiguration:
        procedureName: DeleteConfiguration
        ui_formRefs:
          parameterForm: 'procedures/DeleteConfiguration/ec_parameterForm'
        parameterRefs:
          configuration: config
      retireResource:
        procedureName: Teardown
        parameterRefs:
          resourceName: resName
      retireResourcePool:
        procedureName: Teardown
        parameterRefs:
          resourcePoolName: resName
          configuration: config
      provision:
        procedureName: Provision
        ui_formRefs:
          parameterForm: 'ec_parameterForm'
        parameterRefs:
          configuration: config
          count: count
          resourcePool: resourcePoolName

procedures:

- name: Teardown
  description: Deletes machines from the pool or the specified resource
  hasConfig: false
  parameters:
    - name: resName
      required: true

- name: Delete Machine
  description: Destroys a GCP machine
  hasConfig: true
  parameters:
    - name: instanceName
      required: true
-
  name: 'Provision'
  description: Creates one or few instances from the provided parameters
  hasConfig: true

#  properties:
#    ec_form:
#      - propertyName: configurationParameterRef
#        value: config
#      - propertyName: usesConfigurationNameAsCredential
#        value: 1
#      - propertyName: parameterOptions
#        credentialProtected: true
#        properties:
#          instanceType:
#            path: 'dsl/procedures/Provision/instanceType.groovy'

  parameters:
  - name: instanceNameTemplate
    required: false
    type: entry
    label: Instance Name Template
    documentation: Template for instance name, e.g. my-instance-1. The instance name will be generated by adding a random number to the end of this template.
  - name: instanceType
    required: true
    condition: ${config} != ""
    dependsOn: config
    label: Instance Type
#    serverOptions: 1
    type: entry
    documentation: Instance type, e.g. n1-standard-2
  - name: sourceImage
    required: true
    type: entry
    label: Source Image
    documentation: Source image starting with a project name, e.g. my-project/global/images/image-name
  - name: keys
    type: textarea
    required: false
    label: Keys
    documentation: |
      SSH keys in JSON format, e.g. [{"userName": "user", "key": "ssh-rsa ....."}]
  - name: network
    value: default
    required: true
    type: entry
    label: Network
    documentation: The name of VPC network, e.g. default
  - name: subnetwork
    required: true
    label: Subnetwork
    documentation: The name of VPC subnetwork
    value: default
  - name: diskSize
    required: false
    type: integer
    label: Disk Size
    documentation: Instace disk size in Gb
  - name: instanceTags
    type: textarea
    required: false
    documentation: Instance tags, newline-separated, e.g. my-tag1
    label: Instance Tags
  - name: assignPublicIp
    required: false
    type: checkbox
    checkedValue: true
    uncheckedValue: false
    label: Assign Public IP?
    documentation: If checked, the a NAT network interface will be attached to the instance.
  - name: count
    required: true
    type: integer
    label: Count
    documentation: The number of instances to create.
    value: 1
  - name: resourcePoolName
    required: false
    documentation: If provided, a resource will be created for the instance and placed into this pool.
    label: Resource Pool Name
    type: entry
  - name: resourcePort
    required: false
    value: 7800
    type: entry
    documentation: Agent port for the created resource.
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resourceWorkspace
    required: false
    value: default
    type: entry
    documentation: Workspace name for the resource.
    label: Resource Workspace
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
