pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'EC-GCP-Provision'
  version: '1.1.0'
  description: 'This plugin integrates with Google Cloud Platform to provision new resources from the pre-defined resource templates.'
  author: 'Polina'
  supportUrl: 'pshubina@cloudbees.com'
  category: 'Resource Management'
  shell: 'ec-groovy'

# Plugin configuration description
configuration:
  # This is a shell used for checking connection
  shell: 'ec-groovy'
  # A script for checking connection will be generated
  checkConnection: 'true'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
  -
    name: config
    documentation: The name for the created configuration
    required: true
    type: entry
    label: Configuration Name
  -
    name: desc
    documentation: Description for the configuration
    required: false
    type: entry
    label: Description
  -
    name: projectId
    documentation: Project ID of the project in GCP under which Instances are provisioned.
    required: true
    type: entry
    label: Project Id
  -
    name: zone
    required: true
    type: entry
    documentation: Zone name, e.g. us-east1-b
    label: Zone
  -
    name: credential
    documentation: |
      Service account key in JSON format. For example,

      {
        "type": "service_account",
        "project_id": "PROJECT ID",
        "private_key_id": "PRIVATE KEY ID",
        "private_key": "-----BEGIN PRIVATE KEY-----PRIVATE KEY CONTENT-----END PRIVATE KEY-----\n",
        "client_email": "SERVICE ACCOUNT NAME@PROJECT ID.iam.gserviceaccount.com",
        "client_id": "CLIENT ID",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/ACCOUNT ID"
      }

    htmlDocumentation: |
      Service account key in JSON format. For example,<br/>
      <pre>
      {
        "type": "service_account",
        "project_id": "PROJECT ID",
        "private_key_id": "PRIVATE KEY ID",
        "private_key": "-----BEGIN PRIVATE KEY-----PRIVATE KEY CONTENT-----END PRIVATE KEY-----\n",
        "client_email": "SERVICE ACCOUNT NAME@PROJECT ID.iam.gserviceaccount.com",
        "client_id": "CLIENT ID",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/ACCOUNT ID"
      }
      </pre>
    required: true
    type: credential
    credentialType: key
    label: Credential

properties:
  ec_dsl_libraries_path: agent/deps/libs
  ec_configurations: ec_plugin_cfgs
  ec_cloudprovisioning_plugin:
    configurationLocation: ec_plugin_cfgs
    displayName: GCP
    hasConfiguration: 1
    operations:
      createConfiguration:
        procedureName: CreateConfiguration
        ui_formRefs:
          parameterForm: 'procedures/CreateConfiguration/ec_parameterForm'
        parameterRefs:
          configuration: config
      deleteConfiguration:
        procedureName: DeleteConfiguration
        ui_formRefs:
          parameterForm: 'procedures/DeleteConfiguration/ec_parameterForm'
        parameterRefs:
          configuration: config
      retireResource:
        procedureName: Teardown
        parameterRefs:
          resourceName: resName
      retireResourcePool:
        procedureName: Teardown
        parameterRefs:
          resourcePoolName: resName
          configuration: config
      provision:
        procedureName: Provision
        ui_formRefs:
          parameterForm: 'ec_parameterForm'
        parameterRefs:
          configuration: config
          count: count
          resourcePool: resourcePoolName

procedures:

- name: Teardown
  description: |
    Deletes Virtual Machines Instance or Instances that correspond to either a Flow Resource or a Flow Resource Pool.
    This procedure essentially calls the Delete Instance procedure followed by removing the Resource from Flow.
  hasConfig: false
  parameters:
    - name: resName
      required: true
      type: textarea
      label: Resource name or pool name
      documentation: Flow resource name or pool name

- name: Delete Instances
  description: Destroys one or more Virtual Machine Instances in GCP.
  hasConfig: true
  parameters:
    - name: instanceNames
      required: true
      type: textarea
      label: Instance Names
      htmlDocumentation: |
          Instance name.<br/>
          In case of multiple instances, specify one instance name per line.
      documentation: |
          Instance name.
          In case of multiple instances, specify one instance name per line.
    - name: timeoutSeconds
      label: Timeout in Seconds
      documentation: Time (in seconds) to wait for instances to be deleted.
      value: 300
      type: integer
#
#- name: Cleanup Instances
#  hasConfig: true
#  parameters:
#    - name: filter
#      type: textarea
#    - name: age
#      type: entry
#      documentation: Instance age in hours
#    - name: dryRun
#      type: checkbox
#      checkedValue: true
#      uncheckedValue: false

- name: Run Script
  description: Runs a custom groovy script using the GCP client.
  hasConfig: true
  parameters:
    - name: script
      type: textarea
      label: Script
      required: true
      htmlDocumentation: |
        Script to evaluate.
        This is an example:
        <pre>
        println "Compute raw client: $compute"
        println "Project ID: $project"
        println "Zone: $zone"
        println "Flow Client: $ef"
        println "Compute Wrapper: $wrapper"
        </pre>
      value: |
        println "Compute raw client: $compute"
        println "Project ID: $project"
        println "Zone: $zone"
        println "Flow Client: $ef"
        println "Compute Wrapper: $wrapper"

  outputParameters:
    output: Some output parameter to use in the script. Evaluation result (the last value returned by the script) will be saved into this parameter.


- name: Stop Instances
  hasConfig: true
  description: Stops one or more Virtual Machine Instances in GCP.
  parameters:
    - name: instanceNames
      required: true
      htmlDocumentation: |
        Instance name.
        In case of multiple instances, specify one instance name per line.
      label: Instance Names
      type: textarea
    - name: timeout
      required: false
      label: Timeout
      type: integer
      documentation: Time (in seconds) to wait for instances to be deleted.

- name: Start Instances
  hasConfig: true
  description: Starts one or more Virtual Machine Instances in GCP.
  parameters:
    - name: instanceNames
      type: textarea
      required: true
      htmlDocumentation: |
        Instance name.<br/>
        In case of multiple instances, specify one instance name per line.
      label: Instance Names
    - name: resultProperty
      required: true
      value: '/myJob/result'
      type: entry
      label: Result Property Sheet
      documentation: |
        Property Sheet to store instances that are started in JSON format.
  outputParameters:
    instances: JSON representation of instances

- name: List Instances
  description: List Virtual Machine instances in GCP.
  hasConfig: true
  parameters:
    - name: filter
      label: Filter
      htmlDocumentation: |
        Filter expression used to filter resources. The filter expression must specify the field name,
        a comparison operator, and the value used to filter them.<br/><br/>
        The value must be a string, a number, or a boolean and the comparison operator must be either =, !=, &gt;, or &lt;.<br/>
        For example, name != foobar-instance will exclude all Virtual Instances named foobar-instance.
      required: false
      type: textarea

    - name: maxResults
      label: Max Results
      type: integer
      requred: false
      documentation: |
        The maximum number of results per page that should be returned. If the number of available results is larger than maxResults, Compute Engine returns a nextPageToken that can be used to get the next page of results in subsequent list requests. Acceptable values are 0 to 500, inclusive. (Default: 500)
    - name: orderBy
      label: Order By
      documentation: |
        Order used to sort results.

        By default results are sorted in alphanumerical order of resource name. In addition results can be sorted in descending order of time stamp by using orderBy="creationTimestamp desc". This sorts results based on the creationTimestamp field in reverse chronological order (newest result first).

        Currently, only sorting by name or creationTimestamp desc is supported.
      type: entry
      required: false
    - name: resultProperty
      type: entry
      value: /myJob/instances
      required: true
      label: Result Property Sheet
      documentation: Property Sheet used to store JSON representation of instances found.

  outputParameters:
    instances: JSON representation of instances found.

- name: Reset Instances
  hasConfig: true
  description: Reset one or more Virtual Machine Instances in GCP.
  parameters:
    - name: instanceNames
      required: true
      type: textarea
      htmlDocumentation: |
        Instance name.<br/>
        In case of multiple instances, specify one instance name per line.


#- name: Update Instances
#  hasConfig: true
#  description: Updates instances parameters
#  parameters:
#    - name: instanceNames
#      type: textarea
#      required: true
#      label: Instance Names
#      documentation: Newline-separated instance names
#    - name: networkTags
#      type: textarea
#      required: false
#    - name: deletionProtection
#      type: radio
#      options:
#        - name: retain
#        - name: on
#        - name: off

-
  name: 'Provision'
  description: Creates one or more Virtual Machine instances.
  hasConfig: true

#  properties:
#    ec_form:
#      - propertyName: configurationParameterRef
#        value: config
#      - propertyName: usesConfigurationNameAsCredential
#        value: 1
#      - propertyName: parameterOptions
#        credentialProtected: true
#        properties:
#          instanceType:
#            path: 'dsl/procedures/Provision/instanceType.groovy'

  outputParameters:
    instanceDetails: Details of the Instance created.
  parameters:
  - name: instanceNameTemplate
    required: false
    type: entry
    label: Instance Name Template
    htmlDocumentation: |
      Name of the instance template e.g. my-instance-1.<br/>
      The instance name is typically generated by adding a random string to the end of this name.
  - name: instanceType
    required: true
    condition: ${config} != ""
    dependsOn: config
    label: Instance Type
    type: entry
    documentation: Instance type, e.g. n1-standard-2
  - name: sourceImage
    required: false
    type: entry
    label: Source Image
    htmlDocumentation: |
      Source image starting with a project name, e.g. my-project/global/images/image-name.<br/>
      Either URL or family should be provided.
  - name: sourceImageProject
    label: Source Image Project
    htmlDocumentation: |
      Project to which Source Image belongs.<br/>
      If not specified, the project from the configuration will be used.
  - name: sourceImageFamily
    label: Source Image Family
    type: entry
    htmlDocumentation: |
      Source Image family.<br/>
      Either the family or a URL should be provided.
  - name: keys
    type: textarea
    required: false
    label: Keys
    documentation: |
      SSH keys in JSON format, e.g. [{"userName": "user", "key": "ssh-rsa ....."}]
  - name: network
    value: default
    required: true
    type: entry
    label: Network
    documentation: The name of the VPC network, e.g. default.
  - name: subnetwork
    required: true
    label: Subnetwork
    documentation: The name of the VPC subnetwork
    value: default
  - name: diskSize
    required: false
    type: integer
    label: Disk Size
    documentation: Instace disk size in Gb
  - name: instanceTags
    type: textarea
    required: false
    documentation: Instance tags, newline-separated, e.g. my-tag1
    label: Instance Tags
  - name: assignPublicIp
    required: false
    type: checkbox
    checkedValue: true
    uncheckedValue: false
    label: Assign Public IP?
    documentation: If checked, a NAT network interface will be attached to the instance.
  - name: useServiceAccount
    type: radio
    required: false
    options:
      - name: No Service Account
        value: noAccount
      - name: Same Service Account
        value: sameAccount
      - name: Another Service Account
        value: anotherAccount
    value: noAccount
    label: Use Service Account
    htmlDocumentation: |
      If specified, the Service Account used to provision the virtual machine.
      Options are as follows.<br/><br/>

      <ul>
      <li>None - No Service Account is used.</li>
      <li>Same - Use the Service Account as in the plugin configuration.</li>
      <li>Another - Use the Service account as specified in the Service Account email field. In this case the expectation is that the Service Account used in the plugin configuration has privileges to access this other service account.</li>
      </ul>
  - name: serviceAccountEmail
    label: Service Account Email
    dependsOn: useServiceAccount
    condition: ${useServiceAccount == 'anotherAccount'}
    type: entry
    required: false
    documentation: Service account email to use with the provisioned machine.
  - name: deletionProtection
    type: checkbox
    checkedValue: true
    uncheckedValue: false
    label: Protect from Deletion?
    documentation: If checked, the instance will be protected from deletion.
  - name: instanceHostname
    type: entry
    required: false
    label: Hostname
    documentation: Hostname for the instance
  - name: count
    required: true
    type: integer
    label: Count
    documentation: The number of instances to create.
    value: 1
  - name: pingResource
    type: checkbox
    label: Ping Resource?
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
    required: false
    value: false
    checkedValue: true
    uncheckedValue: false
    htmlDocumentation: If checked, the resource will be pinged and the job will finish successfully only when the resource is up and running.
  - name: waitTimeout
    type: integer
    label: Timeout in Seconds
    value: 300
    htmlDocumentation: |
        If specified, time to wait for provisioning to finish (in seconds).
  - name: resourcePoolName
    required: false
    documentation: If specified, the resource will be created for the instance and placed into this pool.
    label: Resource Pool Name
    type: entry
  - name: resourcePort
    required: false
    value: 7800
    type: entry
    documentation: Agent port for the created resource.
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resourceWorkspace
    required: false
    value: default
    type: entry
    documentation: Workspace name for the created resource.
    label: Resource Workspace
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resourceZone
    type: entry
    documentation: Zone to use for the created resource
    label: Resource Zone
    required: false
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resultProperty
    value: /myJob/result
    type: entry
    required: false
    documentation: Property sheet to store instance result.
    label: Result Property

- name: Create Image
  hasConfig: true
  description: Creates a new Virtual Machine image in GCP
  parameters:
    - name: family
      type: entry
      required: false
      label: Family
      documentation: |
        Name of the Image family.
        Either image family name or image name should be provided.
        If the image name is not provided, it will be calculated from the family name.
    - name: name
      required: false
      label: Name
      documentation: |
        Name of the image.
        Either image family name or image name should be provided.
        If the image name is not provided, it will be calculated from the family name.
    - name: source
      type: radio
      label: Source
      htmlDocumentation: |
        Source from which Image is created. It should be one of the following:
        <ul>
        <li>Source Disk</li>
        <li>Source Snapshot</li>
        <li>Source Image</li>
        </ul>
      options:
        - name: Source Disk
          value: sourceDisk
        - name: Source Snapshot
          value: sourceSnapshot
        - name: Source Image
          value: sourceImage
      value: sourceDisk
    - name: sourceDisk
      type: entry
      required: false
      label: Source Disk
      dependsOn: source
      condition: ${source == 'sourceDisk'}
      documentation: Name of the Source Disk.
    - name: diskZone
      required: false
      documentation: |
        Zone of the Source Disk.
        If Source Disk is chosen, this field should be specified.
      dependsOn: source
      label: Disk Zone
      condition: ${source == 'sourceDisk'}
    - name: sourceSnapshot
      type: entry
      required: false
      label: Source Snapshot
      dependsOn: source
      condition: ${source == 'sourceSnapshot'}
      documentation: Snapshot for the source image.
    - name: sourceImage
      type: entry
      required: false
      documentation: Name of the Source image.
      dependsOn: source
      label: Source Image
      condition: ${source == 'sourceImage'}
    - name: description
      label: Description
      documentation: Description for the new image.
      required: false
      type: textarea
    - name: diskSizeGb
      label: Disk Size (GB)
      type: integer
      required: false
      documentation: Disk size in GB
    - name: deprecateOld
      type: checkbox
      checkedValue: true
      uncheckedValue: false
      label: Deprecate Old Image?
      value: false
      documentation: If checked, the old image from the same family will be deprecated and replaced with the new image
    - name: forceCreate
      type: checkbox
      checkedValue: true
      uncheckedValue: false
      value: false
      label: Force Create?
      documentation: If checked, the image will be created even if the disk is in use by a running instance.
    - name: locations
      type: textarea
      label: Locations
      required: false
      documentation: Space or newline-separated zone names for the new image. By default the new image will be multi-zonal.
