pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'EC-GCP-Provision'
  version: '1.0.0'
  description: 'This plugin integrates with Google Cloud Platform to provision new resources from the pre-defined resource templates.'
  author: 'Polina'
  supportUrl: 'pshubina@cloudbees.com'
  category: 'Resource Management'
  shell: 'ec-groovy'

# Plugin configuration description
configuration:
  # This is a shell used for checking connection
  shell: 'ec-groovy'
  # A script for checking connection will be generated
  checkConnection: 'true'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
  -
    name: config
    documentation: The name for the created configuration
    required: true
    type: entry
    label: Configuration Name
  -
    name: desc
    documentation: Description for the configuration
    required: false
    type: entry
    label: Description
  -
    name: projectId
    documentation: Project ID for the main project
    required: true
    type: entry
    label: Project Id
  -
    name: zone
    required: true
    type: entry
    documentation: Zone name, e.g. us-east1-b
    label: Zone
  -
    name: credential
    documentation: Service account key in JSON format
    required: true
    type: credential
    credentialType: key
    label: Credential

properties:
  ec_dsl_libraries_path: agent/deps/libs
  ec_configurations: ec_plugin_cfgs
  ec_cloudprovisioning_plugin:
    configurationLocation: ec_plugin_cfgs
    displayName: GCP
    hasConfiguration: 1
    operations:
      createConfiguration:
        procedureName: CreateConfiguration
        ui_formRefs:
          parameterForm: 'procedures/CreateConfiguration/ec_parameterForm'
        parameterRefs:
          configuration: config
      deleteConfiguration:
        procedureName: DeleteConfiguration
        ui_formRefs:
          parameterForm: 'procedures/DeleteConfiguration/ec_parameterForm'
        parameterRefs:
          configuration: config
      retireResource:
        procedureName: Teardown
        parameterRefs:
          resourceName: resName
      retireResourcePool:
        procedureName: Teardown
        parameterRefs:
          resourcePoolName: resName
          configuration: config
      provision:
        procedureName: Provision
        ui_formRefs:
          parameterForm: 'ec_parameterForm'
        parameterRefs:
          configuration: config
          count: count
          resourcePool: resourcePoolName

procedures:

- name: Teardown
  description: Deletes machines from the resource pool or the specified resource
  hasConfig: false
  parameters:
    - name: resName
      required: true
      type: textarea
      label: Resource name or pool name
      documentation: Flow resource name or pool name

- name: Delete Instances
  description: Destroys GCP machines
  hasConfig: true
  parameters:
    - name: instanceNames
      required: true
      type: textarea
      label: Instance Names
      documentation: Newline-separated instance names to delete
    - name: timeoutSeconds
      label: Timeout in Seconds
      documentation: Timeout to wait for instances to be deleted in seconds
      value: 300
      type: integer
#
#- name: Cleanup Instances
#  hasConfig: true
#  parameters:
#    - name: filter
#      type: textarea
#    - name: age
#      type: entry
#      documentation: Instance age in hours
#    - name: dryRun
#      type: checkbox
#      checkedValue: true
#      uncheckedValue: false

- name: Run Script
  description: Runs a custom groovy script with the prepared GCP client
  hasConfig: true
  parameters:
    - name: script
      type: textarea
      label: Script
      required: true
      documentation: |
        Script to evaluate. The following variables are accessible:

        compute - compute client
        ef - ElectricFlow Groovy API client
        zone - zone name from the configuration
        project - project ID from the configuration
        wrapper - Compute wrapper from this plugin

        Both wrapper and compute clients are already initialized.

      value: |
        println "Compute raw client: $compute"
        println "Project ID: $project"
        println "Zone: $zone"
        println "Flow Client: $ef"
        println "Compute Wrapper: $wrapper"

  outputParameters:
    output: Some output parameter to use in the script


- name: Stop Instances
  hasConfig: true
  description: Stops GCP instances
  parameters:
    - name: instanceNames
      required: true
      documentation: Newline separated instance names
      label: Instance Names
      type: textarea
    - name: timeout
      required: false
      value: -1
      label: Timeout
      type: integer
      documentation: Timeout in seconds to wait for the instances to stop. -1 means no timeout.

- name: Start Instances
  hasConfig: true
  description: Starts GCP instances
  parameters:
    - name: instanceNames
      type: textarea
      required: true
      documentation: Newline separated instance names
      label: Instance Names
    - name: resultProperty
      required: true
      value: '/myJob/result'
      type: entry
      label: Result Property Sheet
  outputParameters:
    instances: JSON representation of instances

- name: List Instances
  description: Lists instances for the provided parameters
  hasConfig: true
  parameters:
    - name: filter
      label: Filter
      documentation: |
        A filter expression that filters resources listed in the response. The expression must specify the field name, a comparison operator, and the value that you want to use for filtering. The value must be a string, a number, or a boolean. The comparison operator must be either =, !=, >, or <.

        For example, if you are filtering Compute Engine instances, you can exclude instances named example-instance by specifying name != example-instance.
      required: false
      type: textarea

    - name: maxResults
      label: Max Results
      type: integer
      requred: false
      documentation: |
        The maximum number of results per page that should be returned. If the number of available results is larger than maxResults, Compute Engine returns a nextPageToken that can be used to get the next page of results in subsequent list requests. Acceptable values are 0 to 500, inclusive. (Default: 500)
    - name: orderBy
      label: Order By
      documentation: |
        Sorts list results by a certain order. By default, results are returned in alphanumerical order based on the resource name.

        You can also sort results in descending order based on the creation timestamp using orderBy="creationTimestamp desc". This sorts results based on the creationTimestamp field in reverse chronological order (newest result first). Use this to sort resources like operations so that the newest operation is returned first.

        Currently, only sorting by name or creationTimestamp desc is supported.

      type: entry
      required: false
    - name: resultProperty
      type: entry
      value: /myJob/instances
      required: true
      label: Result Property Sheet

  outputParameters:
    instances: JSON representation of instances found

- name: Reset Instances
  hasConfig: true
  description: Reset GCP instances
  parameters:
    - name: instanceNames
      required: true
      type: textarea
      documentation: Newline-separated instance names


#- name: Update Instances
#  hasConfig: true
#  description: Updates instances parameters
#  parameters:
#    - name: instanceNames
#      type: textarea
#      required: true
#      label: Instance Names
#      documentation: Newline-separated instance names
#    - name: networkTags
#      type: textarea
#      required: false
#    - name: deletionProtection
#      type: radio
#      options:
#        - name: retain
#        - name: on
#        - name: off

-
  name: 'Provision'
  description: Creates one or few instances from the provided parameters
  hasConfig: true

#  properties:
#    ec_form:
#      - propertyName: configurationParameterRef
#        value: config
#      - propertyName: usesConfigurationNameAsCredential
#        value: 1
#      - propertyName: parameterOptions
#        credentialProtected: true
#        properties:
#          instanceType:
#            path: 'dsl/procedures/Provision/instanceType.groovy'

  outputParameters:
    instanceDetails: Details for the created instances
  parameters:
  - name: instanceNameTemplate
    required: false
    type: entry
    label: Instance Name Template
    documentation: Template for instance name, e.g. my-instance-1. The instance name will be generated by adding a random number to the end of this template.
  - name: instanceType
    required: true
    condition: ${config} != ""
    dependsOn: config
    label: Instance Type
    type: entry
    documentation: Instance type, e.g. n1-standard-2
  - name: sourceImage
    required: false
    type: entry
    label: Source Image
    documentation: Source image starting with a project name, e.g. my-project/global/images/image-name. Either URL or family should be provided.
  - name: sourceImageProject
    label: Source Image Project
    documentation: Source image project. If not set, the project from the configuration will be used.
  - name: sourceImageFamily
    label: Source Image Family
    type: entry
    documentation: Source image family. Either family or URL should be provided.
  - name: keys
    type: textarea
    required: false
    label: Keys
    documentation: |
      SSH keys in JSON format, e.g. [{"userName": "user", "key": "ssh-rsa ....."}]
  - name: network
    value: default
    required: true
    type: entry
    label: Network
    documentation: The name of VPC network, e.g. default
  - name: subnetwork
    required: true
    label: Subnetwork
    documentation: The name of VPC subnetwork
    value: default
  - name: diskSize
    required: false
    type: integer
    label: Disk Size
    documentation: Instace disk size in Gb
  - name: instanceTags
    type: textarea
    required: false
    documentation: Instance tags, newline-separated, e.g. my-tag1
    label: Instance Tags
  - name: assignPublicIp
    required: false
    type: checkbox
    checkedValue: true
    uncheckedValue: false
    label: Assign Public IP?
    documentation: If checked, the a NAT network interface will be attached to the instance.
  - name: useServiceAccount
    type: radio
    required: false
    options:
      - name: No Service Account
        value: noAccount
      - name: Same Service Account
        value: sameAccount
      - name: Another Service Account
        value: anotherAccount
    value: noAccount
    label: Use Service Account
    documentation: |
      Which service account will be used by the provisioned machine. If same service account is chosen, the service account that
      is provided by the plugin configuration will be used. If another service account is chosen, the service account in the plugin configuration
      must have access to this service account.
  - name: serviceAccountEmail
    label: Service Account Email
    dependsOn: useServiceAccount
    condition: ${useServiceAccount == 'anotherAccount'}
    type: entry
    required: false
    documentation: Service account email to use with the provisioned machine.
  - name: deletionProtection
    type: checkbox
    checkedValue: true
    uncheckedValue: false
    label: Protect from Deletion?
    documentation: If checked, the instance will be protected from deletion.
  - name: instanceHostname
    type: entry
    required: false
    label: Hostname
    documentation: Hostname for the instance
  - name: count
    required: true
    type: integer
    label: Count
    documentation: The number of instances to create.
    value: 1
  - name: waitTimeout
    type: integer
    label: Timeout in Seconds
    value: 300
    documentation: Time to wait for the operation to finish (in seconds). Please note that the resource availability is NOT checked.
  - name: resourcePoolName
    required: false
    documentation: If provided, a resource will be created for the instance and placed into this pool.
    label: Resource Pool Name
    type: entry
  - name: resourcePort
    required: false
    value: 7800
    type: entry
    documentation: Agent port for the created resource.
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resourceWorkspace
    required: false
    value: default
    type: entry
    documentation: Workspace name for the resource.
    label: Resource Workspace
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resourceZone
    type: entry
    documentation: Zone to use for the created resource
    label: Resource Zone
    required: false
    dependsOn: resourcePoolName
    condition: ${resourcePoolName} != ""
  - name: resultProperty
    value: /myJob/result
    type: entry
    required: false
    documentation: Property sheet to store instance result
    label: Result Property

- name: Create Image
  hasConfig: true
  description: Creates a new image
  parameters:
    - name: family
      type: entry
      required: false
      label: Family
      documentation: |
        Image family for the new image. If the image name is not provided the new image name will be calculate from the
        family name. Either image name or a family name must be provided.
    - name: name
      required: false
      label: Name
      documentation: |
        Name for the new image. If the name is not provided, the family must be provided and the
        image name will be calculated from the family name.
        Either image name or a family name must be provided.
    - name: source
      type: radio
      label: Source
      options:
        - name: Source Disk
          value: sourceDisk
        - name: Source Snapshot
          value: sourceSnapshot
        - name: Source Image
          value: sourceImage
      value: sourceDisk
    - name: sourceDisk
      type: entry
      required: false
      label: Source Disk
      dependsOn: source
      condition: ${source == 'sourceDisk'}
      documentation: Source disk name for the image.
    - name: diskZone
      required: false
      documentation: Zone for the source disk if the source disk is used.
      dependsOn: source
      condition: ${source == 'sourceDisk'}
    - name: sourceSnapshot
      type: entry
      required: false
      label: Source Snapshot
      dependsOn: source
      condition: ${source == 'sourceSnapshot'}
      documentation: Snapshot for the source image.
    - name: sourceImage
      type: entry
      required: false
      documentation: Source image name
      dependsOn: source
      label: Source Image
      condition: ${source == 'sourceImage'}
    - name: description
      label: Description
      documentation: Description for the new image.
      required: false
      type: textarea
    - name: diskSizeGb
      label: Disk Size (GB)
      type: integer
      required: false
      documentation: Disk size in GB
    - name: deprecateOld
      type: checkbox
      checkedValue: true
      uncheckedValue: false
      label: Deprecate Old Image?
      value: false
      documentation: If checked, the old image from the same family will be deprecated and replaced with the new image
    - name: forceCreate
      type: checkbox
      checkedValue: true
      uncheckedValue: false
      value: false
      label: Force Create?
      documentation: |
        If checked, the image will be created if the disk is in use by a running instance.
    - name: locations
      type: textarea
      label: Locations
      required: false
      documentation: Space or newline-separated zone names for the new image. By default the new image will be multi-zonal.